### ISSUE TITLE
Create a trackmaster unified box

### ISSUE THREAD

**Issue by ThirteenFish** [psas/Launch-12#10]
The current trackmaster is a collection of mostly COTS parts attached to a board. It would be really great if we took all of them out of their casings and put them all in one box, possibly with the antenna mounted to it too. That way we have a single unified box that can be moved from the TM3K to RocketTracks, to whatever else we want to attach it to.

**Comment by natronics** [comment]
Thanks to Gavin, this is done!

![2015-06-28 20 41 27](https://cloud.githubusercontent.com/assets/146144/8400598/24657242-1dd6-11e5-8f0f-829264cbe4eb.jpg)
