### ISSUE TITLE
LTC GPIO Relays and sensors

### ISSUE THREAD

**Issue by ThirteenFish** [psas/Launch-12#12]
Phidgets are a pain to deal with, and a GPIO powered Relay bank  or sensors could be much easier to deal with.

**Comment by nellump** [comment]
BeagleBone Black GPIO reference:
- http://kilobaser.com/blog/2014-07-15-beaglebone-black-gpios

**Comment by andrewgreenberg** [comment]
This is happening for LTC3: see https://github.com/psas/launch-tower

Not happening for Launch 12, so closing this issue.
