### ISSUE TITLE
Payload: Opal v2

### ISSUE THREAD

**Issue by ThirteenFish** [psas/Launch-12#15]
Make data go up. Apparently the v2 has some really neat sensors, and it will be ready by the September launch.

**Comment by aSmig** [comment]
@andrewgreenberg is there an Opal v2 ready to strap on the rocket or should we call this a won't-fix?

**Comment by andrewgreenberg** [comment]
Done! Needs two switches, but we'll live: one for the battery, and one for the "temporary on" via the Geiger counter board via the RaspiCam2.
