### ISSUE TITLE
Get more valve grease for assembling the motor, we're almost out.

### ISSUE THREAD

**Issue by dsigma** [psas/Launch-12#16]
Dow 111 Valve Lubricant
http://www.amazon.com/DOW-111-Lubricant-Sealant-5-3/dp/B00CTUJNU2

**Comment by dsigma** [comment]
Andrew, order this!

**Comment by natronics** [comment]
Mentioning a username with an `@` symbol in front, like @andrewgreenberg should ping him. But I don't think he ever really checks github, so It might be like yelling into an empty canyon :sweat_smile:

**Comment by andrewgreenberg** [comment]
I totally get emails. For all of this, so it's now on my radar.

Andrew

## 

---

Andrew Greenberg

Electrical and Computer Engineering
Portland State University
http://www.ece.pdx.edu/

## adg@ece.pdx.edu  C: 503.708.7711

**Comment by andrewgreenberg** [comment]
Done! Will arrive by this Friday.
