### ISSUE TITLE
 Make payload aeroshell fit better

### ISSUE THREAD

**Issue by andrewgreenberg** [psas/Launch-12#18]
We _have_ to be able to easily remove the payload module's aeroshell, yet it's incredibly hard to do. Investigate and fix the interference so that becomes easy.

**Comment by dsigma** [comment]
Dawn dish washing soap :)

**Comment by natronics** [comment]
Sanding the aluminium frame down slightly. In progress.

**Comment by andrewgreenberg** [comment]
Jeremy did some more, and now the payload aeroshell fits "OK". Doesn't even hurt to press it on! Closing this issue.
