### ISSUE TITLE
Add connectors between recovery module and payload module

### ISSUE THREAD

**Issue by andrewgreenberg** [psas/Launch-12#19]
The lack of connectors is simply untenable: the increased risk of adding a connector is far offset by the pain in the ass of the wiring and strain relief of the wires. For the love of god, connectorize the pyrotechnics.

**Comment by andrewgreenberg** [comment]
Just ordered HXT 2mm connectors to be connected to all recovery system components. When we add those connectors, they should be carefully labeled so that we can't cross connect them (NSR vs line cutters).

**Comment by NickCarter2** [comment]
Labeling is fine but much better imho if you can physically key them to prevent incorrect wiring. Also you can color code them with paint or code the wire insulation colors. Keying could be done by gluing pieces of material onto the connectors so the wrong ones will physically not mate.

**Comment by aSmig** [comment]
Gavinated! (polarity keyed and colour coded.)
