### ISSUE TITLE
Fix launch control canopies

### ISSUE THREAD

**Issue by andrewgreenberg** [psas/Launch-12#21]
No matter what, we need a better launch control area that is bigger and more wind proof. Current best thoughts:
- Purchase two more pop-up tents.
- Purchase 8 "dog leash" screws.
- Purchase 8 cinch down straps.
- Purchase 16 tent stakes.
- Figure out how to use one or more of the sides, to block out a lot of the sun on the E/W sides of the tent.

**Comment by nellump** [comment]
A tarp stretched between the canopy framework and ground might work as both a sun screen and tie-down.

**Comment by dsigma** [comment]
There are some extra cloth/canvas parts in the shed still in their original wrappers. This might be side walls? not sure...

**Comment by andrewgreenberg** [comment]
Yes, these are the original side walls. I also have some at my house. I'll bring them in so we can have them all together.

**Comment by dsigma** [comment]
We should have a single tub that has all the parts for the tents. The side-walls, the stakes, the sand screws. I want to "grab-and-go"...

**Comment by aSmig** [comment]
The wind fixed the canopies real good.
