### ISSUE TITLE
Lite Weight Launch Tower

### ISSUE THREAD

**Issue by dsigma** [psas/Launch-12#23]
The current launch tower is extremely heavy, and requires a minimum of 6 people for over an hour to setup and tear down. This is an inefficient process, stemming from the weight and basic design of the tower.

Ideas for new tower design:
- Aluminum trusses used by A/V production. The best option would be to use (3) of the 4.92ft truss sections. This is the easiest to deal with logistically. These come with a separate coupler piece when you buy each truss. You can use a stainless steel hex bolt with a lock not on the 'lower' half, and a snap-pin on the upper half for easy assembly/disassembly.
  - An 8.2ft length is 27lbs. A 9.8ft length is 31 lbs. I can lift either of these with one hand! Total tower weight would be on the order of 60-70 lbs, which two people can easily put up.
  - http://www.cheaplights.com/cart/page107.html
  - If we got (3) of the 4.92ft trusses, it could easily fit into normal cars, or the bed of a truck.
  - If we got two 8.2 ft lengths, it would give us a 16ft tall tower, and each length could easily fit in a 10ft trailer.
  - If we got two of the 9.8ft lengths, we may need to bump up to the 12ft long trailer, and it makes it harder to carry in long bed pickup (which is 8ft long). 
- Use nylon tie down ratchet straps. These can hold thousands of pounds, fold up easily, are super lite, pack tightly, and the ratchet action for adjustment is far easier then turnbuckles and chains. These are also standard-items for OROC launch towers and have a history of success and common use. Try to get red if possible, it's important that they are easy to see so as to avoid people running into them.
  - Use ratchet straps with snap hooks:  http://www.amazon.com/SecureMyCargo-Ratchet-Strap-Snap-hook-Yellow/dp/B00J9U5NMM/ref=sr_1_5?ie=UTF8&qid=1430848136&sr=8-5&keywords=2%22+ratchet+straps+snap+hook
  - These are super strong: https://www.google.com/search?site=&tbm=isch&source=hp&biw=2144&bih=979&q=car+tire+strap+tie+down
  - http://www.amazon.com/Erickson-58629-Yellow-Ratchet-Floating/dp/B00ISL4NWE/ref=sr_1_1?ie=UTF8&qid=1424312947&sr=8-1&keywords=ratchet+straps+20
  - 
- Use fiberglass pole for antenna bar. It's super lite.
- Use aluminum or stainless steel for the various mechanical components used to mount the rail to the tower. These will not have rust issues.
- For parts that need to connect together, use locking pins with a square or round lock. Similar to this: http://www.mcmaster.com/#98416a012/=sxuqkb
- For the rail mounting hardware, consider having pivoting  mechanisms such that the hardware can be recessed into the interior of the truss. This simplifies storage and transport.
- Consider using a ball-joint rod end to pivot the tower rail on. This will allow for off-angle rail with out binding up when trying to put it together. Something like this: http://www.mcmaster.com/#59915k277/=vyxlra
  - Have some kind of auto-alignment mechanism at the bottom. Perhaps two compression springs at 45 degree angles on either side, or use some kind of trick with gravity to get it to self-align vertically.
- If possible, designing it such that 2 people can put up the whole tower in under 30 minutes.
- Have some kind of quick-mount for the tower computer to hang or hook onto the back of the tower. Hanging the computer should take one person less then 30 seconds to do.
- Use fasteners that will not rust. Stainless Steel is fine, so is aluminum and fiberglass.

**Comment by natronics** [comment]
We bought a nice aluminum one!!!11!!eleven!!
