### ISSUE TITLE
Replace hex bolts on tower with quick-pins

### ISSUE THREAD

**Issue by dsigma** [psas/Launch-12#25]
If we can avoid needing wrenches it will speed up tower assembly.
A locking pin, something similar to this, affixed via string to the relevant location, would be quick and easy to put in. 

The loads for the tower sections are in sheer, so these pins are perfectly suited to this job.

**Comment by dsigma** [comment]
Tubing is 1.25" in diamater

**Comment by dsigma** [comment]
Order 10 of these:
Zinc-Plated Steel Pin with Wire Lock
Round Retainer with Tab, 1/4" Diameter, 1-3/4" Usable Length
http://www.mcmaster.com/#98416a211/=syprgk
$2.16 each

**Comment by LateralGs** [comment]
I just picked up this http://www.harborfreight.com/20-piece-pto-pin-assortment-67534.html from HarborFreight.  It has 10x 1/4 by 1-3/4" pins like the ones you want.  You are welcome to have them.

**Comment by dsigma** [comment]
Sweet! Let's try them on the next launch, and hopefully just end up replacing the launch tower with a super lite version later! :)

Thanks! :)

**Comment by dsigma** [comment]
We have a new tower that is all pin based
