### ISSUE TITLE
Replace Steel Tower Antenna bar with fiberglass bar that's shorter

### ISSUE THREAD

**Issue by dsigma** [psas/Launch-12#26]
The current antenna bar is big and heavy, probably 10-15 pounds. This could easily be replaced with a half-pound fiberglass bar.

I don't think the current antenna bar needs to be so long. I think that 2 or 3 feet would be long enough. Someone with good RF foo should confirm this.

**Comment by dsigma** [comment]
Design Idea
- (2) pieces of flat bar clamped to each of the tower poles
- Holes in the flat bar for a U-bolt to hold it on the tower
- 3rd hole in flat bar for a standard machine threaded eye bolt
- Pass the fiberglass tube through the two eye bolts
- Have holes in the fiberglass rod such that you can put locking pins through the pole, and have it retain against the inside face of either eye bolt. This will keep it from sliding out
- Attach some kind of clamp to the bar to keep it rotated in a fixed position.

**Comment by dsigma** [comment]
Tower Truss poles are 1.25" in diameter, and 11.125" apart (center-to-center)

**Comment by natronics** [comment]
New tower has a redesigned attachment.
