### ISSUE TITLE
Tower computer hook

### ISSUE THREAD

**Issue by dsigma** [psas/Launch-12#27]
We currently need to screw two pipe clamps onto the tower box, then try to clamp those onto the back of the tower. This can take 5-10 minutes as we have to spend time futzing with fasteners and hardware and have multiple people hold it.

I'd like a way to have a simple hook, or something, such that the tower computer can be mounted in under 30 seconds, by one person, with zero tools.

**Comment by nellump** [comment]
On Mon, Jul 21, 2014 at 06:22:56PM -0700, Dave Camarillo wrote:

> I'd like a way to have a simple hook, or something, such that the
> tower computer can be mounted in under 30 seconds, by one person,
> with zero tools.

Assuming the tower uprights are a suitable distance apart, and the LTC
enclosure isn't getting shaken severely, cabinet hangers like these
might work well:

  http://www.mcmaster.com/#17565a31/=sxv89r

## 

Paul Mullen

**Comment by dsigma** [comment]
Yeah, that's a great design! That's exactly what I'd want. If we can find a beefy version, that can handle transport and storage too, that would be good. The design is also simple enough that a little work on some aluminum flat bar and we could easily fabricate one.
