### ISSUE TITLE
Make Elderberry A Python Module

### ISSUE THREAD

**Issue by ThirteenFish** [psas/Launch-12#3]
Copy of [this L-11 issue](https://github.com/psas/Launch-11/issues/12)

Finish converting all the events to an event library and make the repo entirely python. At this point we can make it a python module (using setuptools) and include it in av3-fc in the requirements.txt file instead of as a submodule.

Also makes it much cleaner for use in other projects.

**Comment by natronics** [comment]
Moved to the relevant repo:

https://github.com/psas/psas_packet/issues/5
