### ISSUE TITLE
Make a permanent PSAS road sign, if we don't already have one?

### ISSUE THREAD

**Issue by dsigma** [psas/Launch-12#33]

**Comment by nellump** [comment]
For future launches from the Brothers site, multiple road signs might be helpful: one marking the "green gate" road, and two more, one each a mile in either direction from the turn, advising drivers that they're getting close.  It's awful dark out there at night, and things go by fast at highway speeds.

**Comment by nellump** [comment]
A reflective, roll-up, diamond-shaped road sign like this would be ideal:
- http://www.signsdirect.com/Home/Mesh-Roll-Up-Sign-Faces/36-Custom-Inscription-Sign-Face-With-Frame.html

Unfortunately, they're ~$130+ each with reflective coating.  Corrugated plastic signs and a sandwich board stand is a lot cheaper.  A stand with a sign for each side is ~$110:
- http://www.signsdirect.com/Home/24x36-Upload-Art/24x36-Custom-4mm-Coroplast-Sign.html
- http://www.signsdirect.com/Home/The-signicade/Signicade-Portable-Sign-Stand.html

**Comment by nellump** [comment]
Or a set of old-fashioned construction barricades:
- http://www.discountsafetygear.com/traffic-barricade-type-1.html?id=21619610058&gclid=CLm-tMyi_78CFQIvaQodh78AfQ

We could hand-letter our own signs to save money.  For that matter, making our own barricades wouldn't be that much work.  How poor are we?

**Comment by dsigma** [comment]
I would personally vote for something small and lite weight. If it were some kind of fabric, with metal grommets in the corners and some carabiners and/or bungee cords that would be great. Super light weight, small, and can easily attach to the metal gate or to the cylinder of stones that the gate is attached to.

**Comment by nellump** [comment]
Small and light-weight are great, but a sign hanging on the Green Gate isn't much use for after-dark stragglers.  I had a difficult time just finding the gate itself.  A sign set back from the highway shoulder wouldn't have helped.

I would think that a sufficiently rigid, reasonably lightweight sandwichboard sign could be made out of 1"x2" lumber and 1/4" plywood.  I'll even volunteer to make the first prototype.

**Comment by dsigma** [comment]
Yes, very true! I guess as long as it's lite weight and easy to setup it would be fine...

**Comment by nellump** [comment]
Well, if the sandwichboard signs turn out to be too unwieldy, we can always drill a giant hole into each and repurpose them as cornhole (beanbag toss) games.

**Comment by nellump** [comment]
Regarding sign lettering, we could create stencils with the laser cutter.  What are the maximum X/Y dimensions of the cutter (i.e., how big of a stencil could be cut in it)?

**Comment by natronics** [comment]
I like the lettering idea. I could probably pull off hand lettering but the laser cutter in the lab can do about 20"x12". That's make some huge lettering.

**Comment by BartMassey** [comment]
Either cut cardboard stencils with the laser cutter or just buy [letter stencils](http://amazon.com/dp/B0012E0LHU). Then get [reflective spray paint](http://amazon.com/dp/B000LNVC1M) and/or [glow-in-the-dark spray paint](http://amazon.com/dp/B000GLG7HS). You should be able to make a lovely plywood sign.

**Comment by LateralGs** [comment]
I have plywood, I have silver paint, I have some retro-reflective tape... This would be easy to do.  What color do we want the background to be?  Also anything other than just the large lettering "PSAS" ?

**Comment by andrewgreenberg** [comment]
No, I think that's it. However, I hate to be a slave to yet another piece of large plywood... maybe we we could go with that sign corregated plastic?

**Comment by LateralGs** [comment]
If its going to be a free standing sign that sits at the road side it really should have some weight to it.  Otherwise the wind could knock it over easily.  I am thinking a simple sandwich board type sign with two pieces of plywood and a hinge at the top.  I have a 34"x48" sheet of plywood so the sign would be 17"x24".

**Comment by andrewgreenberg** [comment]
Oh! A sandwich board. OK, sure. 17 x 24 seems reasonable. I always imagined plastic or fabric that we bundie to the gate itself.

**Comment by dsigma** [comment]
I was really hoping for something that is cloth based, that we can just bungee to the green metal gate... Super lite, easy to pack and store, minimal space...

**Comment by LateralGs** [comment]
From the feedback in this thread it sounds like people want something visible at night on the road side.  If its attached to the gate it may be hard to see in a passing car.  I may also have some green cloth that i could also make a sign out of.

**Comment by vosechu** [comment]
I had agreed to take this on last week, but if @LateralGs is willing to take it over that would probably be wise. Stupid new job preventing me from doing the things I actually want to do...

**Comment by natronics** [comment]
![2015-07-14 19 26 04](https://cloud.githubusercontent.com/assets/146144/8689576/47f55972-2a5e-11e5-9fc5-92f9791f7442.jpg)
