### ISSUE TITLE
Create multiple git repos for airframe CAD drawings

### ISSUE THREAD

**Issue by dsigma** [psas/Launch-12#38]
Define a list of git repos for PSAS CAD. Take the existing dropbox folder, split up the various sub folders into individual repos. Split along the lines of "common" parts, such as electronic/avionics boards and fasteners, motor casings. Also split by module (recovery module, tail module, camera module, payload module etc). Setup top-level repo for the high level full rocket assembly, which will reference parts and assemblies in the other modules.

**Comment by dsigma** [comment]
Proposed Repos:
- sw-cad-airframe-lv2.3     - Includes nosecone, recovery, 360 camera, roll control, payload, avionics and tail modules and top level assembly
- sw-cad-airframe-lv3.0      LV3 carbon fiber airframe parts and assemblies
- sw-cad-airframe-common     3rd party motor casings, other parts common to multiple airframes
- sw-cad-avionics    - circuit boards, such as the ARTS2, telemetrum, atom etc
- sw-cad-common   - fasteners, common hardware
- sw-cad-launch-tower
- sw-cad-rocket-tracks

**Comment by natronics** [comment]
We came up with:
- [sw-cad-airframe-lv2.3](https://github.com/psas/sw-cad-airframe-lv2.3)
  - [sw-cad-airframe-lv3.0](https://github.com/psas/sw-cad-airframe-lv3.0)
- [sw-cad-common](https://github.com/psas/sw-cad-common)
- [sw-cad-avionics](https://github.com/psas/sw-cad-avionics)
- [sw-cad-airframe-rollcontrol](https://github.com/psas/sw-cad-airframe-rollcontrol)
- [sw-cad-airframe-nsr](https://github.com/psas/sw-cad-airframe-nsr)
- [sw-cad-airframe-umbilical-disconnect](https://github.com/psas/sw-cad-airframe-umbilical-disconnect)
