### ISSUE TITLE
Replace nylon red cord on tower with Kevlar

### ISSUE THREAD

**Issue by dsigma** [psas/Launch-12#39]
The current rope stretches a lot. When we're loading the rocket, it causes the rail to lower, putting it at an angle, and causing the launch lugs to bind and making it difficult to slide the rocket onto the rail.

We can replace the nylon cord with Kevlar cord that won't stretch, thereby avoiding this problem.

Also, Kevlar is mostly fireproof. Great for being in proximity of rocket exhaust.

**Comment by natronics** [comment]
#nofix for this launch
