### ISSUE TITLE
Launch Tower: Weather Station

### ISSUE THREAD

**Issue by ThirteenFish** [psas/Launch-12#41]
We've had various people in the past work on a weather station that interfaced with the LTC for the launch tower that measured things like wind speed and temperature, but it's never been completed. This would be a cool thing to have for a launch sometime.

**Comment by nellump** [comment]
We must have an ultrasonic anemometer.  I'll look into our options.

**Comment by andrewgreenberg** [comment]
Not happening for Launch 12; moving to Launch 13
