### ISSUE TITLE
Cleanup machining on launch rail buttons

### ISSUE THREAD

**Issue by dsigma** [psas/Launch-12#46]
We had to manually dremel the rail buttons, so they look pretty bad. These need to be put on a lathe and turned to clean them up.

**Comment by dsigma** [comment]
I took some measurements of the rail:
A:
0.405"
0.408"
0.411"
0.409"
0.409"
0.412"

B: From top and bottom ends
0.231"
0.231"
0.232"
0.235"

For clearance, we want to add/subtract to the largest/smallest of the measured dimensions. 
For the A dimension, I think we should add 0.075", so 0.405-0.075=0.330"
For the B dimension, target 0.240".
Katia and Eric, can you measure the current lugs and see how they actually compare to these numbers? What were the actual measurements? The EPL should have a pair of calipers if you need to borrow some... 

![rail_side_view](https://cloud.githubusercontent.com/assets/3642002/3752708/d0f37a68-180a-11e4-8666-a999761ac97b.jpg)

**Comment by wicker** [comment]
Awesome! In the future, can we make a point to include images that have been resized down from "whaaaaat just happened to my data plan?" to merely 800x600 or 640x480 size?

**Comment by dsigma** [comment]
oh, yeah, sorry about that! I just snapped a pic and uploaded... I'll resize in the future... :)

**Comment by wicker** [comment]
Much appreciated!

**Comment by andrewgreenberg** [comment]
We're down to exactly one launch rail buttons / lugs, so getting at least three of these in good working order is now critical.

**Comment by natronics** [comment]
Jordan brought in several newly machined ones on Tuesday.
