### ISSUE TITLE
Redesign rocket carrier/stand

### ISSUE THREAD

**Issue by LateralGs** [psas/Launch-12#48]
The rocket carrier worked well as a work stand when setting up the rocket.  To further our goal of lighter, more compact storage and transport of tools a new rocket carrier will be developed using 3 pieces of 4ft 8020 (1530 Ultra Lite?) and a set of bolt on legs.  Tool holders should be made to hang on the sides.  This new version will be a stationary work space for assembling and holding the rocket.  A separate project will be for a method to carry the rocket since it came to light that the current carrier did not fulfill that task optimally.

A requirement is that the whole thing support a 10ft + rocket weighing at least 80lb (use 100lb as target for calculations).  Using the existing supports with 15 series aluminum extrusion design is recommended.

**Comment by dsigma** [comment]
In the spirit of previous discussions, keeping it lite-weight, able to setup by one (or two) people, with no tools would be nice... Also, if it can be labeled such that it can be figured out by someone who has not seen or worked with it before that would be nice...

**Comment by LateralGs** [comment]
Using carriage bolts and wing nuts seems to work well for the no tools requirement.  The rest could be labeled or color coded to show joining sections.  Basically place the instructions right on the frame.

**Comment by LateralGs** [comment]
Current design in SolidWorks.
- 3x 4ft 1530 main rail
- Uses existing adjustable legs with new static braces to the frame.
- New rocket supports
  - Roller skate wheels for rotating rocket easily (80mm 78A)
  - Tie down posts for securing rocket
  - Clearance for tail fins
  - Cam locks for easy position adjustment

![rocket_stand](https://cloud.githubusercontent.com/assets/5344225/3789865/fc80286a-1acc-11e4-9f6e-e6843394f143.png)
![roller_support](https://cloud.githubusercontent.com/assets/5344225/3789876/3e0e15b6-1ace-11e4-90cc-673b89721c45.png)

**Comment by dsigma** [comment]
I like the design! :)

Would it be worthwhile to make more then 4 stands? I recall at the last launch they all got used up on individual modules while assembling the rocket. E.G. 2 stands for one module, total of 4 stands means only 2 module sections max on the stand at a time. It might be good to have extra stands to allow for more individual module sections at a time.

Do the legs bolt on? or pivot out of he way for transport? something else?

**Comment by LateralGs** [comment]
The legs bolt on.  I did not like how the folding legs worked, we could look at making these fold but I don't see the need for something that is a work stand and not a carrier.  One of the folding parts also got damaged due to force being applied in the wrong direction when people were trying to figure out how to fold them up.  Any of the parts that need to be assembled on site will be carriage bolts with wing nuts.  All other permanent fasteners will be secured with lock nuts or t-nuts and torqued down.

I agree we probably want more than 4 supports, 6 being probably enough.  Tuesday we should have a design review and go over it in more detail.

**Comment by natronics** [comment]
I guess I'm not closing this issue, because I'm waiting for the rollers :)

Feature request: could we have and extra holder for the nosecone? It's usually not attached so it needs it's own support. A simple one would be fine.

**Comment by BartMassey** [comment]
Aren't we supposed to have a CF airframe that weighs less than 20lbs RSN? if so, why do we still need a 100lb rocket carrier, or any carrier at all?

**Comment by LateralGs** [comment]
This is not to carry the rocket.  Instead it is intended as a stationary work platform for the rocket.  It also provides a way to display the rocket when we are at events.  There is a separate light weight carrying mechanism planned.

**Comment by natronics** [comment]
I'm closing this, for the purposes of this launch it's finished.
