### ISSUE TITLE
Redesign method for carrying rocket (recovery/setup)

### ISSUE THREAD

**Issue by LateralGs** [psas/Launch-12#49]
Carrying the rocket with 4 people is sufficient given they can easily maneuver around obstacles and hold the weight of the rocket in a comfortable way.  The current rocket carrier which is now being redesigned as a work stand for the rocket was manageable for recovery but had unnecessary weight and size.  The proposed design for the new method of carrying the rocket is with two poles with brackets on them that get strapped to the airframe of the rocket providing two perpendicular poles to the rocket for lifting.  The poles should be long enough that each of the 4 people can adjust position laterally while walking.  Making these poles light weight will also aid in reducing the overall carrying mass.  A suggestion is to use light weight conduit pipe of about 1 to 1.5 inches in diameter with a wood support in the middle to cradle the rocket when it is strapped down.  Similar in idea to timber carriers used for moving large logs.

**Comment by dsigma** [comment]
It might be helpful if the suspension under the poles was a single point (or rope), which would allow two people on either side of the rocket to be at a non-90 degree angle with respect to the rocket. I would forsee cases where one person has to navigate over brush more quickly then the opposite person, which would change the angle of the pole. A single point rope would allow it to pivot easily. On a side note, timber carriers do the swivel/pivot thing too... :)

The cradle should be designed such that the rocket won't move length-wise through the cradle. If it slides, it may hit the camera or the roll control canards on the cradle. A strap or something going over the top of the rocket body may do the trick. 

I would also suggest having some kind of fast hook, or clip, or clamp type of quick connect method. If it only took a moment to do the final connect that would be great.

**Comment by dsigma** [comment]
Another thought, this may be helpful for loading the rocket on the launch rail. If there were a mode where you could sling a "U" shape under the rocket, with sufficient space to put the rail under the pole but above the rocket, it would ease putting it on the launch rail.

**Comment by LateralGs** [comment]
My thought was to have the carrier work both on the bottom and top of the rocket.  With possibly some short legs to keep it above the ground when you have it in the under rocket position.  This would allow it to be placed on the ground if needed without the rocket touching and room for peoples fingers around the poles.

A pivot and quick clamp are both things I was considering incorporating.  The simplest attachment would be a ratchet strap that binds the rocket to the U support.  I will see about doing some design drawings or models by Tuesday.

**Comment by LateralGs** [comment]
![Timber Carrier](http://shopequipment.tpub.com/TM-9-243/img/TM-9-243_256_3.jpg)

For those that like pictures here is a timber carrier being used. :)

**Comment by LateralGs** [comment]
Current design in SolidWorks.
- 5ft galvanized pipe for handle (length may change)
- Swivel pivot in center
- Optional stand that can be attached to support rocket
- Can be mounted top or bottom
- Nylon strap holds rocket
- Quick release latch used to lock nylon strap
- Padding or non marring material will be used to protect rocket surface

![rocket_lift](https://cloud.githubusercontent.com/assets/5344225/3789889/2a8eda24-1acf-11e4-87fa-27c76425c46b.png)
![rocket_lift_legs](https://cloud.githubusercontent.com/assets/5344225/3789890/2d7e2c58-1acf-11e4-8a39-bc4d5cfb6c87.png)

**Comment by dsigma** [comment]
This is super cool! Nice design! :)

Is it designed to allow you to rotate the rocket from the bottom to the top? Seems like you could pivot the steel bars so they are inline with the rocket, rotate, then pivot back to 90 degrees... Otherwise trying to pivot a 5ft bar might be a pain.

We should add some kind of hook or pin or carabiner to the ends of the bars, such that they can positively lock to truck bed wall mount points. 

Also, we now have all our solidworks drawings in github. If you clone all the "sw-cad-*" repositories into the same directory, then maybe make a sub directory somewhere in the sw-cad-common repo, that would be a good place for CAD drawings.

Cheers!
-d

**Comment by LateralGs** [comment]
The steel bars rotate fully so you can put them inline with the rocket.  Hopefully it is used mostly in the bottom position and rotating the rocket will not be needed.  With it on the bottom you can always set it down on the ground.  With the added space in the new rocket stand roller supports the lift will have clearance to be on the bottom.

Thanks for pushing all the cad files they are useful for reference in these designs.  I was going to ask where to put the cad files and sw-cad-common seems like a good enough place.

Lets go over this design on Tuesday in more detail.

**Comment by LateralGs** [comment]
These are done.  Currently they use a wooden pole to reduce weight.  If deemed not strong enough a steel pole will be used instead.
![rocket_lift](https://cloud.githubusercontent.com/assets/5344225/8513074/ea939800-2311-11e5-9000-fe8244e3666f.jpg)

**Comment by dsigma** [comment]
Rad! If you need a piece of steel pole, there is a section that used to be used for the antenna masts that you can use... It's probably 1.5in in diameter...

**Comment by LateralGs** [comment]
I think that is the same pole Andrew sent home with me on Tuesday.

**Comment by dsigma** [comment]
Humm, perhaps we have 2 then? I also have one...

**Comment by LateralGs** [comment]
Well that solves the problem of getting a second one.  Can you bring it on Tuesday?

**Comment by dsigma** [comment]
will do!
