### ISSUE TITLE
Find or make a case or box for the TeleMetrum Yagi Antenna

### ISSUE THREAD

**Issue by dsigma** [psas/Launch-12#50]
The Yagi antenna is fragile, and during transport we don't want to damage it.

I'd like a case or box to safely store this in during transport. This could be as fancy as a plastic brief case with custom cut out foam in it it, or as simple as a cardboard box with some hot-glued chunks of foam in bottom.

The yagi is 27" x 14" x 1.5"
http://arrowantennas.com/arrowii/440-5ii.html

Note: disassembling this into a tube has been suggested, but I don't want to have to "do stuff" while we're out in the field. I want to pick it up out of the box, and plug it into the USB port. That's it...

**Comment by nellump** [comment]
Instead of a carrying case that the antenna must be removed from prior to flight, perhaps a sturdy radome that the antenna can be semi-permanently mounted in, and only removed for (hopefully unnecessary) servicing?

**Comment by natronics** [comment]
We made a quick one for this launch.
