### ISSUE TITLE
Debug Rocket Ready

### ISSUE THREAD

**Issue by ThirteenFish** [psas/Launch-12#51]
During L-11 the Rocket Ready signal failed to function. I've spent some time debugging it and it appears to be caused by the flight umbilical segment mounted to the interior of the avionics airframe section. 

With all dev umbilical segments attached Rocket Ready works correctly. When the interior flight umbilical is attached the Rocket Ready line functions correctly from the GPIO pin to R167, but passed that point is always low, as if it were shorted to ground. I've examined the flight umbilical with a multimeter and it does not appear that the Rocket Ready line is shorted to another wire or the airframe. Further more it is as far as I can tell connected to the correct pin on both connectors.

**Comment by aSmig** [comment]
Andrew says: Gavin totally screwed up by not checking Andrew's uhh uhh terrible mistakes.  Rocket ready and umbilical were switched on the silkscreen layer of the PCB for the 18-pin rocket net connector.  Silkscreen fixed and avionics module umbilical fixed.
