### ISSUE TITLE
Update firmware on old TeleMetrum and TeleDongle

### ISSUE THREAD

**Issue by dsigma** [psas/Launch-12#52]
- There was a new release of AltOS that needs to be flashed on the older TM and TD
- The version of firmware on the old TeleDongle may be for the wrong rev of PCB. Check the version and make sure it's the latest version for that rev of PCB

**Comment by andrewgreenberg** [comment]
Didn't we purchase a new Telemetrum? Has that been mounted yet? Any software updates on that?

**Comment by dsigma** [comment]
I updated firmware on the TM2 to version 1.6.

I was unable to update the firmware on the teledongle because the 4 pin and 8 pin MicroMaTch
 connectors are not soldered on the PCB. Do we have any of those? Seems like it should have come with them soldered on?

**Comment by BartMassey** [comment]
Keithp will be back in town tomorrow. You can probably get a micromatch from him if you don't have any handy elsewhere. You might want to just get a TD3, which can be flashed via USB.

**Comment by andrewgreenberg** [comment]
Added debug and companion connectors to our v0.2b TeleDongle, and then used the two TeleDongles to update themselves. We're now up and running and version 1.6.
