### ISSUE TITLE
Tools and parts holder for rocket stand

### ISSUE THREAD

**Issue by LateralGs** [psas/Launch-12#53]
The rocket stand will be redesigned with T channel aluminum extrusion (8020).  It would be nice to have some tool holders and some bins that fit into these holders for rocket assembly.  My thought is that this could be done using the laser cut bamboo with the castellated edges that fit together.  To hang these on the rocket stand would require only two or three 5/16" holes for t bolts that fit into the aluminum channel.  Wing nuts/washers can be used to secure the box so that it can be fully assembled by hand.  Optionally you could also incorporate small magnetic parts trays into the design (of which we have two small ones).

With the box construction you will need to design and cut the material along with gluing it together.  Discuss the design of this with Gavin if you choose to take this on.  It is a simple ME project that probably can be done in an evening or two at the PSAS meetings and EPL.

**Comment by LateralGs** [comment]
80/20 Inc., 1530-ULS, 15 Series, 1.5" x 3" Ultra Lite Smooth T-Slotted Extrusion x 48"

5/16 holes for bolts, center line spacing between parallel t-slots on the side is 1.5 inches.

![1530 ULS](http://8020.net/Images/Hover-1530_ULS-1.gif)

**Comment by andrewgreenberg** [comment]
OMG this is totally done and a brilliant combination of IKEA and Gavin. Gavi-KEA. IKavin. Something. 

And.... done.
