### ISSUE TITLE
VMS Trailer

### ISSUE THREAD

**Issue by dsigma** [psas/Launch-12#58]
We've decided to use the VMS trailer this year.

Proposed trailer modifications
- Add an antenna mast mount. This would be a telescoping mast, from ham radio outlet or online. We can mount a female threaded mount point to the upper back corner of the trailer, and a clamp mount to the lower corner. The mast can then be pivoted down, adjusted, and pivoted back up. It's important to not have a protruding mount so as to avoid head injuries. The mast mount should use a hand-knob, or other tool-less fastening method to connect it to the trailer.
- Add more tie-down mounting bars. Use the same type as are already in the trailer, but extended to additional portions of the trailer.
- Add some cool PSU/PSAS/VMS stickers to the side of the trailer.

Logistics
- Reserve the trailer the Monday before the launch
- On Tuesday, tow the trailer to the back of the FAB building and everyone (like 30 people) loads the trailer. Re-park the trailer in the lot.
- On Saturday morning, drive to PSU and hitch up the trailer and drive to brothers. 
- Do the launch
- Sunday night, park the trailer in it's normal parking spot by campus
- Tuesday, tow the trailer back to the back side of FAB building and have 30 people unload the trailer.
- Wednesday, trailer is officially released back to the rest of the department for others to use.

**Comment by natronics** [comment]
Trailer is reserved for launch.

Antenna mast is now part of the Flight Director Table.
