### ISSUE TITLE
Replace plug on TM3K USB to BBB coaxial power cable

### ISSUE THREAD

**Issue by andrewgreenberg** [psas/Launch-12#65]
The cable that powers the BBB on the TM3K is bad. If you twist the wire, you can kill the power. Replace it.

**Comment by vosechu** [comment]
+:100:. I've done that multiple times and didn't notice until I had exhausted all the difficult testing things.

**Comment by aSmig** [comment]
Gavin resolved this with his new tm4k.  Thanks @LateralGs !!!
