### ISSUE TITLE
Replace ground strap on BQ3060 FUSE pin with resistor

### ISSUE THREAD

**Issue by ThirteenFish** [psas/Launch-12#7]
Duplicate of [this issue](https://github.com/psas/Launch-11/issues/39) from L-11

OK, this was more complicated than I expected. It turns out FUSE has two functions: 1) as an output which blows a chemical fuse and 2) as an input which shuts down the output transistors if an external battery protection IC pulls it high. It turns out 2 is DEFAULT (bastards), so you have to pull this to ground to get the BQ3060 to work.

There is a VERY low probability that we could accidentally flip this to state (1), and then the BQ3060 could brown out or blow itself up if it asserts the FUSE pin. So eventually, we should replace the ground strap with like a 4.7kohm resistor to ground.

**Comment by andrewgreenberg** [comment]
If it asserts the fuse pin, and blows up, then this is OK because it'll stop driving the charge/discharge MOSFETs. Also, it's a rocket, not a pacemaker. Closing this.
