### ISSUE TITLE
Clamp Integrator In PID

### ISSUE THREAD

**Issue by natronics** [psas/Launch-12#71]
Dan sayz: in case we get large values in the integrator (see: integrator windup).

**Comment by wrh2** [comment]
Implemented code to clamp integrator in roll-control/simulation/PIDcontroller.py for testing purposes. Also implemented code to clamp integrator in av3-fc/src/rollcontrol.c for the actual flight. Max and min for integrator still need to be fine tuned.

**Comment by wrh2** [comment]
Fine tuned integrator clamp and pushed to av3-fc/src.
