### ISSUE TITLE
Examine the Geiger counter log

### ISSUE THREAD

**Issue by jameysharp** [psas/Launch-12#78]
Did we see anything interesting/surprising during the flight?

**Comment by ghost** [comment]
Not so much but it was fun to look.
Notes in: data/geiger.ipynb in commit fc22b11b88b129602b8a4d1d11ce6edf8463b6bf

**Comment by natronics** [comment]
Nice work K!!

https://github.com/psas/Launch-12/blob/gh-pages/data/geiger.ipynb

Given sensitivity of the device and height we went I'm not all too surprised at the [lack of] result. Pretty interesting though. Should we consider this closed?

**Comment by ghost** [comment]
Closing the issue.
