### ISSUE TITLE
 Re-examine cell balancing settings in BQ3060

### ISSUE THREAD

**Issue by ThirteenFish** [psas/Launch-12#8]
Duplicate of [this](https://github.com/psas/Launch-11/issues/49) L-11 issue.

The default cutoffs for cell balancing in the BQ3060 are pretty big - 50 mV. 1% of 4.2V is 42 mV, so this is right on the border of what we care about for EOC voltage regulation. There's a TI app note on BQ3060 cell balancing, which indicates tight tolerancing is 10 mV and loose is 40 mV. I vote we eventually change this to 0.5% of full charge voltage, which would be somewhere around 4.2 V \* 0.5% = 21 mV.

There's no rush on this, and this does not have to be done pre-flight.

**Comment by andrewgreenberg** [comment]
No need to do this; the cells are balanced well enough and this doesn't seem to be an issue, so we're closing this issue.
